bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.3
env: DISPLAY=:99.0
before_script:
  - "mysql -e 'create database rest_assured_test;'"
  - "sh -e /etc/init.d/xvfb start"
script: "bundle exec rspec --color spec && bundle exec cucumber --format progress"
branches:
  only:
    - master
notifications:
  email: false
