bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.1
env: DISPLAY=:99.0
addons:
  postgresql: "9.3"
before_script:
  - "createuser -d root && createdb rest_assured_test -U root"
  - "sh -e /etc/init.d/xvfb start"
script: "bundle exec rspec spec && bundle exec cucumber --format progress"
branches:
  only:
    - master
notifications:
  email: false
