bundler_args: --without development
sudo: false
# Travis bug, see https://github.com/bundler/bundler/pull/3559
cache: bundler
before_install: gem update bundler
rvm:
  - 2.2.2
  - 2.4.1
env: DISPLAY=:99.0
services:
  - postgresql
before_script:
  - "createdb rest_assured_test"
script: "bundle exec rspec spec && bundle exec cucumber"
branches:
  only:
    - master
